### ISSUE TITLE
`MODULE_NOT_FOUND` with `corepack use pnpm@next-12`

### ISSUE THREAD

**Issue by MikeMcC399** [nodejs/corepack#873]
- relates to https://github.com/nodejs/corepack/issues/775#issuecomment-4973751949

## Current behavior

Executing `corepack use pnpm@next-12` results in an error `MODULE_NOT_FOUND`

## Expected behavior

Corepack should work with pnpm@12. This is however currently ~~an Alpha~~ a ~~Beta~~ release candidate release.

## Steps to reproduce

First reported with: `pnpm@12.0.0-alpha.11`
Reproducible also with: `pnpm@12.0.0-rc.1`

On Ubuntu 24.04.4 LTS, Node.js 24.19.0 LTS, Corepack 0.35.0

```shell
rm -rf ~/.cache/node/corepack
npm uninstall pnpm -g # if previously installed globally
corepack enable pnpm
cd $(mktemp -d)
corepack use pnpm@next-12
```

## Logs

with `export DEBUG=corepack`

```console
$ rm -rf ~/.cache/node/corepack
npm uninstall pnpm -g # if previously installed globally
corepack enable pnpm
cd $(mktemp -d)
corepack use pnpm@next-12

up to date in 198ms
Installing pnpm@12.0.0-alpha.11 in the project...
  corepack Installing pnpm@12.0.0-alpha.11 from https://registry.npmjs.org/pnpm/-/pnpm-12.0.0-alpha.11.tgz +0ms
  corepack Downloading to /home/mike/.cache/node/corepack/v1/corepack-4919-1dff2b33.faa778 +0ms
  corepack LastKnownGood file would be located at /home/mike/.cache/node/corepack/lastKnownGood.json +293ms
  corepack No LastKnownGood version found in Corepack home. +2ms
  corepack Download and install of pnpm@12.0.0-alpha.11 is finished +0ms
  corepack Checking /tmp/tmp.cWjgFyIw1M/package.json +1ms
  corepack Checking /tmp/package.json +0ms
  corepack Checking /package.json +1ms

node:internal/modules/cjs/loader:1520
  throw err;
  ^

Error: Cannot find module '/home/mike/.cache/node/corepack/v1/pnpm/12.0.0-alpha.11/bin/pnpm.mjs'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1517:15)
    at wrapResolveFilename (node:internal/modules/cjs/loader:1071:27)
    at defaultResolveImplForCJSLoading (node:internal/modules/cjs/loader:1095:10)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1122:12)
    at Module._load (node:internal/modules/cjs/loader:1294:5)
    at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
    at executeUserEntryPoint (node:internal/modules/run_main:154:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:89:21) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v24.18.0
```

**Comment by MikeMcC399** [comment]
This issue resembles https://github.com/nodejs/corepack/issues/772 for `pnpm@11.0.0-dev.1005`

Executing the following, using both the latest pre-release, and the latest production pnpm@11, does however work correctly with `corepack@0.35.0`:

```shell
corepack use pnpm@11.0.0-rc.5
corepack use pnpm@latest-11
```

**Comment by MikeMcC399** [comment]
Cross-posted to https://github.com/pnpm/pnpm/issues/13018 in this instance, since it is not clear whether a change is needed to pnpm, or an enhancement is needed to Corepack.

I noticed on https://www.npmjs.com/package/pnpm/v/12.0.0-alpha.11?activeTab=code that the `pnpm@12.0.0-alpha.11` version defines a `preinstall` lifecycle script, which does not exist in pnpm@11.

**Comment by MikeMcC399** [comment]
A triage result is available in https://github.com/pnpm/pnpm/issues/13018#issuecomment-4977765563

**Comment by MikeMcC399** [comment]
This is listed under [pnpm v12 milestone](https://github.com/pnpm/pnpm/milestone/120) and presumably is planned for resolution before pnpm@12 is released.

**Comment by MikeMcC399** [comment]
- https://github.com/pnpm/pnpm/issues/13018 is closed with the comment:

> There is nothing we can do on our end. If we add a backward compatible js shim it will make pnpm startup slower.

**Comment by MikeMcC399** [comment]
https://github.com/nodejs/corepack/pull/887 is now open with a proposal to make Corepack compatible with pnpm@12

**Comment by MikeMcC399** [comment]
This issue is resolved in [pnpm 12.0.0-rc.6](https://github.com/pnpm/pnpm/releases#release-v12.0.0-rc.6) 

## Verification

On Ubuntu 24.04.4 LTS, Node.js 24.19.0 LTS, Corepack 0.35.0

```shell
rm -rf ~/.cache/node/corepack
npm uninstall pnpm -g # if previously installed globally
corepack enable pnpm
cd $(mktemp -d)
corepack use pnpm@next-12
pnpm -v
```

## Logs

```console
$ rm -rf ~/.cache/node/corepack
npm uninstall pnpm -g # if previously installed globally
corepack enable pnpm
cd $(mktemp -d)
corepack use pnpm@next-12

up to date in 151ms
Installing pnpm@12.0.0-rc.6 in the project...

Downloading the pnpm 12.0.0-rc.6 binary for linux-x64...
Already up to date
Done in 24ms using pnpm v12.0.0-rc.6
pnpm -v
12.0.0-rc.6
```
